apiVersion: apps/v1
kind: Deployment
metadata:
  name: entro-deployment
  labels:
    app: entro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: entro
  template:
    metadata:
      labels:
        app: entro
    spec:
      containers:
        - name: entro
          image: gregorym/entro
          ports:
            - containerPort: 3333
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: key
            - name: AWS_REGION
              value: "eu-north-1"
